// AUTO-GENERATED BY generate_roundtrip_tests.py
#include "ams/iface/vita/ControlScheduleRequestPacket.h"
#include "ams/iface/vita/ExtensionDataContextPacket.h"
#include "ams/iface/vita/DataPacket.h"
#include "ams/iface/vita/AckRPacket.h"
#include <iostream>
#include <vector>
#include <string>
#include <cassert>
#include <cstring>
#include <stdexcept>
#include <algorithm>
#include <initializer_list>

using namespace ams::iface::vita;

auto hex_to_words(const std::string& hex) -> std::vector<uint32_t> {
    std::vector<uint32_t> words;
    for (size_t i = 0; i < hex.length(); i += 8) {
        uint32_t word = static_cast<uint32_t>(std::stoul(hex.substr(i, 8), nullptr, 16));
        words.push_back(htonl(word));
    }
    return words;
}

auto host_to_network_words(std::initializer_list<uint32_t> words) -> std::vector<uint32_t> {
    std::vector<uint32_t> network_words(words);
    std::transform(network_words.begin(), network_words.end(), network_words.begin(),
                   [](uint32_t word) { return htonl(word); });
    return network_words;
}
void test_ControlScheduleRequestPacket() {
    std::cout << "Testing ControlScheduleRequestPacket...\n";
    {
        std::string hex = "78e00020a3b1799d00aaaaaa04000a0546685257392456debc8960a901098020972a8469a8a0801e620000000000004000200000212000000822e8f317fc695a9a1de6448fadc1a66b65a6a4de8a774b6c307511a00001c70000000027cd8130562b0f796142ea7dce9ff57fbacfb3d089463e8511ce5dd2a9488d99c5e7ce8a";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ControlScheduleRequestView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ControlScheduleRequestView");
        }
        if (view.getStreamId() != 2746317213U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 586287032288700762ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 11105285438308204966ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 1801823908U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 16035760589027439889ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex8BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 667779376U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 1445662585U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 1631775357U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 3466589567U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 13461175519471353477ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 298737106U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 2840104345U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 3320303242U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ControlScheduleRequestBuilder builder(buf.data(), buf.size());
        builder.setStreamId(2746317213U);
        builder.setTimestampInt(1181241943U);
        builder.setTimestampFracHigh(958682846U);
        builder.setTimestampFracLow(3163119785U);
        builder.setMessageId(2536146025U);
        builder.setScheduleRequestType(2U);
        builder.addBandwidth(586287032288700762ULL);
        builder.addRfRefFreq(11105285438308204966ULL);
        builder.addGain(1801823908U);
        builder.addSampleRate(16035760589027439889ULL);
        builder.setDataFormat(DataFormat::Complex8BitSigned);
        builder.addPolarization(667779376U);
        builder.addPointing3d(1445662585U);
        builder.addBeamWidth(1631775357U);
        builder.addFuncPriorityId(3466589567U);
        builder.addDwell(13461175519471353477ULL);
        builder.addRfFigureOfMerit(298737106U);
        builder.addAddressGroupIndex(2840104345U);
        builder.addTxDigitalInputPower(3320303242U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "78e00021fc377a4c00aaaaaa04000a05daf61a26ddd1dfb2614ff3d7010980e05d65a441a8a0801e620000000400004000200000212000005ec42e08a5e5a5abbaa80dd429d4beef6123fdf78e944239af42e12f200003cf0000000050c187fc448aaa9eb7c93acfa7cad41524933b8323bed01d89fa6a68663f1c97ff5e9ff0827050a8";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ControlScheduleRequestView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ControlScheduleRequestView");
        }
        if (view.getStreamId() != 4231494220U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 6828633549678421419ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 13450015492028022511ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 1629748727U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 10273909465459908911ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 1354860540U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 1149938334U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 3083418319U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getCitedMsgId().value_or(0) != 2815087637U) { throw std::runtime_error("CitedMsgId mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 613628803U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 2575724862190021224ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 1715412119U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 4284391408U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 2188398760U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ControlScheduleRequestBuilder builder(buf.data(), buf.size());
        builder.setStreamId(4231494220U);
        builder.setTimestampInt(3673561638U);
        builder.setTimestampFracHigh(3721519026U);
        builder.setTimestampFracLow(1632629719U);
        builder.setMessageId(1566942273U);
        builder.setScheduleRequestType(14U);
        builder.addBandwidth(6828633549678421419ULL);
        builder.addRfRefFreq(13450015492028022511ULL);
        builder.addGain(1629748727U);
        builder.addSampleRate(10273909465459908911ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(1354860540U);
        builder.addPointing3d(1149938334U);
        builder.addBeamWidth(3083418319U);
        builder.addCitedMsgId(2815087637U);
        builder.addFuncPriorityId(613628803U);
        builder.addDwell(2575724862190021224ULL);
        builder.addRfFigureOfMerit(1715412119U);
        builder.addAddressGroupIndex(4284391408U);
        builder.addTxDigitalInputPower(2188398760U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "78e000241c11f73500aaaaaa04000a05a0a04dc410435a10ff01cf9901098080b88139b9a8a0801e62000000040001400030000021200000a41612931c8eaee96f4cc69a74273ca3e9a1fa6f9be578c72720797d200003cf0000000052fbe43b04fc6d824eb93eff14296c072031d750a8e56e0c2a45c2ab9b49bd26b09b2a5cb683d2e65f987c717394988f3f76be1d";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ControlScheduleRequestView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ControlScheduleRequestView");
        }
        if (view.getStreamId() != 470939445U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 11823658294756421353ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 8020003403116002467ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 3919706735U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 11233517642295835005ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 1392239675U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 83651970U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 1320763135U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getCitedMsgId().value_or(0) != 338258951U) { throw std::runtime_error("CitedMsgId mismatch"); }
        if (view.getModeId().value_or(0) != 540137296U) { throw std::runtime_error("ModeId mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 2833608204U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 3046054765286505766ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getJitter().value_or(0) != 12725811749752918758ULL) { throw std::runtime_error("Jitter mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 1603828849U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1939118223U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 1064746525U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ControlScheduleRequestBuilder builder(buf.data(), buf.size());
        builder.setStreamId(470939445U);
        builder.setTimestampInt(2694860228U);
        builder.setTimestampFracHigh(272849424U);
        builder.setTimestampFracLow(4278308761U);
        builder.setMessageId(3095476665U);
        builder.setScheduleRequestType(8U);
        builder.addBandwidth(11823658294756421353ULL);
        builder.addRfRefFreq(8020003403116002467ULL);
        builder.addGain(3919706735U);
        builder.addSampleRate(11233517642295835005ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(1392239675U);
        builder.addPointing3d(83651970U);
        builder.addBeamWidth(1320763135U);
        builder.addCitedMsgId(338258951U);
        builder.addModeId(540137296U);
        builder.addFuncPriorityId(2833608204U);
        builder.addDwell(3046054765286505766ULL);
        builder.addJitter(12725811749752918758ULL);
        builder.addRfFigureOfMerit(1603828849U);
        builder.addAddressGroupIndex(1939118223U);
        builder.addTxDigitalInputPower(1064746525U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "78e000211064005c00aaaaaa04000a058dcdcd0396a402f201d74256010980103a9bedd4a8a0801e62000000002000400020000021200000e7c99b26dc1110c13ceddf2dab4220a77900f7f9c8dcd19fceb81f9d200003cf000000001825bc54a8b317fa6c6fa6111931e9eeba6c34ab1bf90e27310c0c0023e2fcb42ef91276766ecb15";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ControlScheduleRequestView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ControlScheduleRequestView");
        }
        if (view.getStreamId() != 274989148U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 16702051284283363521ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 4390410598995861671ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 2030106617U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 14473673786760109981ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 405126228U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 2830309370U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 1819256337U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getInfoSource().value_or(0) != 422701550U) { throw std::runtime_error("InfoSource mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 3127653547U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 2015657869714394112ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 602078388U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 788075126U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 1986972437U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ControlScheduleRequestBuilder builder(buf.data(), buf.size());
        builder.setStreamId(274989148U);
        builder.setTimestampInt(2379074819U);
        builder.setTimestampFracHigh(2527331058U);
        builder.setTimestampFracLow(30884438U);
        builder.setMessageId(983297492U);
        builder.setScheduleRequestType(1U);
        builder.addBandwidth(16702051284283363521ULL);
        builder.addRfRefFreq(4390410598995861671ULL);
        builder.addGain(2030106617U);
        builder.addSampleRate(14473673786760109981ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(405126228U);
        builder.addPointing3d(2830309370U);
        builder.addBeamWidth(1819256337U);
        builder.addInfoSource(422701550U);
        builder.addFuncPriorityId(3127653547U);
        builder.addDwell(2015657869714394112ULL);
        builder.addRfFigureOfMerit(602078388U);
        builder.addAddressGroupIndex(788075126U);
        builder.addTxDigitalInputPower(1986972437U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "78e00023134c6c9200aaaaaa04000a0519108be53c835dc0680ac07a010980f00f02bad0a8a0801e62000000042001400020000021200000610461e3fc3d3348747b6dbab7e99aca27a0c3d74bf50b52f7fd5646200003cf00000000bf7b539b0ea2622b284d82e5d9f195d098543881675dd5af91d63f7814fcdd5442c18a623d1a85dd655238a64ccc9bc2";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ControlScheduleRequestView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ControlScheduleRequestView");
        }
        if (view.getStreamId() != 323775634U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 6990820153403192136ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 8393422979251935946ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 664847319U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 5473293373114504774ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 3212530587U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 245522987U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 676168421U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getCitedMsgId().value_or(0) != 3656488400U) { throw std::runtime_error("CitedMsgId mismatch"); }
        if (view.getInfoSource().value_or(0) != 2555656321U) { throw std::runtime_error("InfoSource mismatch"); }
        if (view.getModeId().value_or(0) != 1734202799U) { throw std::runtime_error("ModeId mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 2446737272U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 1512326928856615522ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 1025148381U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1699887270U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 1288477634U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ControlScheduleRequestBuilder builder(buf.data(), buf.size());
        builder.setStreamId(323775634U);
        builder.setTimestampInt(420514789U);
        builder.setTimestampFracHigh(1015242176U);
        builder.setTimestampFracLow(1745535098U);
        builder.setMessageId(251837136U);
        builder.setScheduleRequestType(15U);
        builder.addBandwidth(6990820153403192136ULL);
        builder.addRfRefFreq(8393422979251935946ULL);
        builder.addGain(664847319U);
        builder.addSampleRate(5473293373114504774ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(3212530587U);
        builder.addPointing3d(245522987U);
        builder.addBeamWidth(676168421U);
        builder.addCitedMsgId(3656488400U);
        builder.addInfoSource(2555656321U);
        builder.addModeId(1734202799U);
        builder.addFuncPriorityId(2446737272U);
        builder.addDwell(1512326928856615522ULL);
        builder.addRfFigureOfMerit(1025148381U);
        builder.addAddressGroupIndex(1699887270U);
        builder.addTxDigitalInputPower(1288477634U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
}

void test_ScheduleAckAckRPacket() {
    std::cout << "Testing ScheduleAckAckRPacket...\n";
    {
        std::string hex = "7ce0000f12922f8300aaaaaa04000b05ff002d4d43e42cafeeea163e01008410e1805081000000144000000005000000e117dac35e9953d2286218b8";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckRView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckRView");
        }
        if (view.getStreamId() != 311570307U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getCitedSid().value_or(0) != 3776436931U) { throw std::runtime_error("CitedSid mismatch"); }
        if (view.getRejectReason().value_or(0) != 1587106770U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 677517496U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        AckRBuilder builder(buf.data(), buf.size());
        builder.setStreamId(311570307U);
        builder.setTimestampInt(4278201677U);
        builder.setTimestampFracHigh(1139027119U);
        builder.setTimestampFracLow(4008318526U);
        builder.setMessageId(3783282817U);
        builder.setSchX(true);
        builder.setHasErrors(false);
        builder.addCitedSid(3776436931U);
        builder.addRejectReason(1587106770U);
        builder.addAddressGroupIndex(677517496U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0000fb41b314300aaaaaa04000b05a9d3d7c72260e70f8da010970100841045b89cd90000001440000000050000009ad620abb7b56ea77d106c60";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckRView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckRView");
        }
        if (view.getStreamId() != 3021680963U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getCitedSid().value_or(0) != 2597724331U) { throw std::runtime_error("CitedSid mismatch"); }
        if (view.getRejectReason().value_or(0) != 3082120871U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 2098228320U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        AckRBuilder builder(buf.data(), buf.size());
        builder.setStreamId(3021680963U);
        builder.setTimestampInt(2849232839U);
        builder.setTimestampFracHigh(576775951U);
        builder.setTimestampFracLow(2376077463U);
        builder.setMessageId(1169726681U);
        builder.setSchX(true);
        builder.setHasErrors(false);
        builder.addCitedSid(2597724331U);
        builder.addRejectReason(3082120871U);
        builder.addAddressGroupIndex(2098228320U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0000fd89a40c000aaaaaa04000b0546d483f300e85ecec56811cd01008410430f801d000000144000000005000000bdc14f1f0279b6a6e767dcea";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckRView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckRView");
        }
        if (view.getStreamId() != 3633987776U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getCitedSid().value_or(0) != 3183562527U) { throw std::runtime_error("CitedSid mismatch"); }
        if (view.getRejectReason().value_or(0) != 41531046U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 3882343658U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        AckRBuilder builder(buf.data(), buf.size());
        builder.setStreamId(3633987776U);
        builder.setTimestampInt(1188332531U);
        builder.setTimestampFracHigh(15228622U);
        builder.setTimestampFracLow(3311931853U);
        builder.setMessageId(1125089309U);
        builder.setSchX(true);
        builder.setHasErrors(false);
        builder.addCitedSid(3183562527U);
        builder.addRejectReason(41531046U);
        builder.addAddressGroupIndex(3882343658U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0000f8babce3b00aaaaaa04000b05d5a804eb25e9797720a04502010084104eea04e7000000144000000005000000dc570131e61fecc01a50aec3";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckRView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckRView");
        }
        if (view.getStreamId() != 2343292475U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getCitedSid().value_or(0) != 3696689457U) { throw std::runtime_error("CitedSid mismatch"); }
        if (view.getRejectReason().value_or(0) != 3860851904U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 441495235U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        AckRBuilder builder(buf.data(), buf.size());
        builder.setStreamId(2343292475U);
        builder.setTimestampInt(3584558315U);
        builder.setTimestampFracHigh(636057975U);
        builder.setTimestampFracLow(547374338U);
        builder.setMessageId(1323959527U);
        builder.setSchX(true);
        builder.setHasErrors(false);
        builder.addCitedSid(3696689457U);
        builder.addRejectReason(3860851904U);
        builder.addAddressGroupIndex(441495235U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0000fee0caeb500aaaaaa04000b05dd56cc94cf8ebc5ae1a47e10010084100658663a000000144000000005000000ee49f329cf8d446a444d610b";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckRView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckRView");
        }
        if (view.getStreamId() != 3993808565U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getCitedSid().value_or(0) != 3997823785U) { throw std::runtime_error("CitedSid mismatch"); }
        if (view.getRejectReason().value_or(0) != 3482141802U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1145921803U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        AckRBuilder builder(buf.data(), buf.size());
        builder.setStreamId(3993808565U);
        builder.setTimestampInt(3713453204U);
        builder.setTimestampFracHigh(3482238042U);
        builder.setTimestampFracLow(3785653776U);
        builder.setMessageId(106456634U);
        builder.setSchX(true);
        builder.setHasErrors(false);
        builder.addCitedSid(3997823785U);
        builder.addRejectReason(3482141802U);
        builder.addAddressGroupIndex(1145921803U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
}

void test_ExecutionAckAckXPacket() {
    std::cout << "Testing ExecutionAckAckXPacket...\n";
    {
        std::string hex = "7ce0001b1bac27a700aaaaaa04000c05df465290dbccc47738f16a81010900e03a43b2ba28a0801e620000000000004000200000212000008000743080006d8b80005f30800056a080003e3a8000f88e8000f63b8000e6cf80011b328001d6a680027438800260ec80025616";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckXView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckXView");
        }
        if (view.getStreamId() != 464267175U) { throw std::runtime_error("Stream ID mismatch"); }
        auto ackx_errs = view.getParsedErrorPayloads();
        if (ackx_errs.size() != 13) {
            std::cerr << "Expected 13 error payloads, got " << ackx_errs.size() << " hex: " << hex << "\n";
            std::cerr << "eif0: " << std::hex << view.getEif0() << " eif1: " << view.getEif1() << " eif2: " << view.getEif2() << " eif3: " << view.getEif3() << " eif4: " << view.getEif4() << "\n";
            std::cerr << "view.getPacketSize(): " << (ntohl(words[0]) & 0xFFFF) << "\n";
            throw std::runtime_error("AckX error payloads len mismatch");
        }
        for (uint32_t val : {2147513392U,2147511691U,2147508016U,2147505824U,2147499578U,2147547278U,2147546683U,2147542735U,2147556146U,2147604134U,2147644472U,2147639532U,2147636758U}) {
            bool found = std::any_of(ackx_errs.begin(), ackx_errs.end(),
                                     [val](const ams::iface::vita::AckXView::ErrorPayload& err) {
                                         uint32_t rec = ackx_detail::pack_error_payload(err.subject, err.error_flags, err.error_enum_index);
                                         return rec == val; });
            if (!found) { throw std::runtime_error("AckX error payload missing"); }
        }
        std::vector<uint32_t> buf(2048, 0);
        AckXBuilder builder(buf.data(), buf.size());
        builder.setStreamId(464267175U);
        builder.setTimestampInt(3745927824U);
        builder.setTimestampFracHigh(3687629943U);
        builder.setTimestampFracLow(955345537U);
        builder.setMessageId(977515194U);
        builder.setSchX(false);
        builder.setScheduleRequestType(14U);
        builder.addError(AckXErrorSubject::Bandwidth, 2147513392U & 0xFFF80000U, 2147513392U & 0x3FF);
        builder.addError(AckXErrorSubject::RfRefFreq, 2147511691U & 0xFFF80000U, 2147511691U & 0x3FF);
        builder.addError(AckXErrorSubject::Gain, 2147508016U & 0xFFF80000U, 2147508016U & 0x3FF);
        builder.addError(AckXErrorSubject::SampleRate, 2147505824U & 0xFFF80000U, 2147505824U & 0x3FF);
        builder.addError(AckXErrorSubject::DataFormat, 2147499578U & 0xFFF80000U, 2147499578U & 0x3FF);
        builder.addError(AckXErrorSubject::Polarization, 2147547278U & 0xFFF80000U, 2147547278U & 0x3FF);
        builder.addError(AckXErrorSubject::Pointing3d, 2147546683U & 0xFFF80000U, 2147546683U & 0x3FF);
        builder.addError(AckXErrorSubject::BeamWidth, 2147542735U & 0xFFF80000U, 2147542735U & 0x3FF);
        builder.addError(AckXErrorSubject::FuncPriorityId, 2147556146U & 0xFFF80000U, 2147556146U & 0x3FF);
        builder.addError(AckXErrorSubject::Dwell, 2147604134U & 0xFFF80000U, 2147604134U & 0x3FF);
        builder.addError(AckXErrorSubject::RfFigureOfMerit, 2147644472U & 0xFFF80000U, 2147644472U & 0x3FF);
        builder.addError(AckXErrorSubject::AddressGroupIndex, 2147639532U & 0xFFF80000U, 2147639532U & 0x3FF);
        builder.addError(AckXErrorSubject::TxDigitalInputPower, 2147636758U & 0xFFF80000U, 2147636758U & 0x3FF);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0001b43f59a8500aaaaaa04000c056f3f920c504d281f82ec9f2d010904c041357e8c28a0801e620000000000004000200000212000008000777d80006c0380005d93800056e980003f738000f88f8000f6a48000e682800118ff8001d66780027679800263448002569c";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckXView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckXView");
        }
        if (view.getStreamId() != 1140169349U) { throw std::runtime_error("Stream ID mismatch"); }
        auto ackx_errs = view.getParsedErrorPayloads();
        if (ackx_errs.size() != 13) {
            std::cerr << "Expected 13 error payloads, got " << ackx_errs.size() << " hex: " << hex << "\n";
            std::cerr << "eif0: " << std::hex << view.getEif0() << " eif1: " << view.getEif1() << " eif2: " << view.getEif2() << " eif3: " << view.getEif3() << " eif4: " << view.getEif4() << "\n";
            std::cerr << "view.getPacketSize(): " << (ntohl(words[0]) & 0xFFFF) << "\n";
            throw std::runtime_error("AckX error payloads len mismatch");
        }
        for (uint32_t val : {2147514237U,2147511299U,2147507603U,2147505897U,2147499891U,2147547279U,2147546788U,2147542658U,2147555583U,2147604071U,2147645049U,2147640132U,2147636892U}) {
            bool found = std::any_of(ackx_errs.begin(), ackx_errs.end(),
                                     [val](const ams::iface::vita::AckXView::ErrorPayload& err) {
                                         uint32_t rec = ackx_detail::pack_error_payload(err.subject, err.error_flags, err.error_enum_index);
                                         return rec == val; });
            if (!found) { throw std::runtime_error("AckX error payload missing"); }
        }
        std::vector<uint32_t> buf(2048, 0);
        AckXBuilder builder(buf.data(), buf.size());
        builder.setStreamId(1140169349U);
        builder.setTimestampInt(1866437132U);
        builder.setTimestampFracHigh(1347233823U);
        builder.setTimestampFracLow(2196545325U);
        builder.setMessageId(1094024844U);
        builder.setSchX(true);
        builder.setScheduleRequestType(12U);
        builder.addError(AckXErrorSubject::Bandwidth, 2147514237U & 0xFFF80000U, 2147514237U & 0x3FF);
        builder.addError(AckXErrorSubject::RfRefFreq, 2147511299U & 0xFFF80000U, 2147511299U & 0x3FF);
        builder.addError(AckXErrorSubject::Gain, 2147507603U & 0xFFF80000U, 2147507603U & 0x3FF);
        builder.addError(AckXErrorSubject::SampleRate, 2147505897U & 0xFFF80000U, 2147505897U & 0x3FF);
        builder.addError(AckXErrorSubject::DataFormat, 2147499891U & 0xFFF80000U, 2147499891U & 0x3FF);
        builder.addError(AckXErrorSubject::Polarization, 2147547279U & 0xFFF80000U, 2147547279U & 0x3FF);
        builder.addError(AckXErrorSubject::Pointing3d, 2147546788U & 0xFFF80000U, 2147546788U & 0x3FF);
        builder.addError(AckXErrorSubject::BeamWidth, 2147542658U & 0xFFF80000U, 2147542658U & 0x3FF);
        builder.addError(AckXErrorSubject::FuncPriorityId, 2147555583U & 0xFFF80000U, 2147555583U & 0x3FF);
        builder.addError(AckXErrorSubject::Dwell, 2147604071U & 0xFFF80000U, 2147604071U & 0x3FF);
        builder.addError(AckXErrorSubject::RfFigureOfMerit, 2147645049U & 0xFFF80000U, 2147645049U & 0x3FF);
        builder.addError(AckXErrorSubject::AddressGroupIndex, 2147640132U & 0xFFF80000U, 2147640132U & 0x3FF);
        builder.addError(AckXErrorSubject::TxDigitalInputPower, 2147636892U & 0xFFF80000U, 2147636892U & 0x3FF);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0001b2095eef600aaaaaa04000c05f0bbac67e71e43a64d0b0d1a0109000049732d6c28a0801e620000000000004000200000212000008000777080006e9380005fb88000578880003f898000f9b58000f7c98000e55b800118ad8001d645800276ae800260bf800255e1";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckXView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckXView");
        }
        if (view.getStreamId() != 546696950U) { throw std::runtime_error("Stream ID mismatch"); }
        auto ackx_errs = view.getParsedErrorPayloads();
        if (ackx_errs.size() != 13) {
            std::cerr << "Expected 13 error payloads, got " << ackx_errs.size() << " hex: " << hex << "\n";
            std::cerr << "eif0: " << std::hex << view.getEif0() << " eif1: " << view.getEif1() << " eif2: " << view.getEif2() << " eif3: " << view.getEif3() << " eif4: " << view.getEif4() << "\n";
            std::cerr << "view.getPacketSize(): " << (ntohl(words[0]) & 0xFFFF) << "\n";
            throw std::runtime_error("AckX error payloads len mismatch");
        }
        for (uint32_t val : {2147514224U,2147511955U,2147508152U,2147506056U,2147499913U,2147547573U,2147547081U,2147542363U,2147555501U,2147604037U,2147645102U,2147639487U,2147636705U}) {
            bool found = std::any_of(ackx_errs.begin(), ackx_errs.end(),
                                     [val](const ams::iface::vita::AckXView::ErrorPayload& err) {
                                         uint32_t rec = ackx_detail::pack_error_payload(err.subject, err.error_flags, err.error_enum_index);
                                         return rec == val; });
            if (!found) { throw std::runtime_error("AckX error payload missing"); }
        }
        std::vector<uint32_t> buf(2048, 0);
        AckXBuilder builder(buf.data(), buf.size());
        builder.setStreamId(546696950U);
        builder.setTimestampInt(4038831207U);
        builder.setTimestampFracHigh(3877520294U);
        builder.setTimestampFracLow(1292569882U);
        builder.setMessageId(1232285036U);
        builder.setSchX(false);
        builder.setScheduleRequestType(0U);
        builder.addError(AckXErrorSubject::Bandwidth, 2147514224U & 0xFFF80000U, 2147514224U & 0x3FF);
        builder.addError(AckXErrorSubject::RfRefFreq, 2147511955U & 0xFFF80000U, 2147511955U & 0x3FF);
        builder.addError(AckXErrorSubject::Gain, 2147508152U & 0xFFF80000U, 2147508152U & 0x3FF);
        builder.addError(AckXErrorSubject::SampleRate, 2147506056U & 0xFFF80000U, 2147506056U & 0x3FF);
        builder.addError(AckXErrorSubject::DataFormat, 2147499913U & 0xFFF80000U, 2147499913U & 0x3FF);
        builder.addError(AckXErrorSubject::Polarization, 2147547573U & 0xFFF80000U, 2147547573U & 0x3FF);
        builder.addError(AckXErrorSubject::Pointing3d, 2147547081U & 0xFFF80000U, 2147547081U & 0x3FF);
        builder.addError(AckXErrorSubject::BeamWidth, 2147542363U & 0xFFF80000U, 2147542363U & 0x3FF);
        builder.addError(AckXErrorSubject::FuncPriorityId, 2147555501U & 0xFFF80000U, 2147555501U & 0x3FF);
        builder.addError(AckXErrorSubject::Dwell, 2147604037U & 0xFFF80000U, 2147604037U & 0x3FF);
        builder.addError(AckXErrorSubject::RfFigureOfMerit, 2147645102U & 0xFFF80000U, 2147645102U & 0x3FF);
        builder.addError(AckXErrorSubject::AddressGroupIndex, 2147639487U & 0xFFF80000U, 2147639487U & 0x3FF);
        builder.addError(AckXErrorSubject::TxDigitalInputPower, 2147636705U & 0xFFF80000U, 2147636705U & 0x3FF);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0001bac3c564000aaaaaa04000c0532fa2de80640be0f12a4def0010904d0624c69b628a0801e620000000000004000200000212000008000773280006df380005d2e8000540b80003cda8000fb668000f5c08000e56880011bb78001d466800275fe800260f8800257a6";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckXView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckXView");
        }
        if (view.getStreamId() != 2889635392U) { throw std::runtime_error("Stream ID mismatch"); }
        auto ackx_errs = view.getParsedErrorPayloads();
        if (ackx_errs.size() != 13) {
            std::cerr << "Expected 13 error payloads, got " << ackx_errs.size() << " hex: " << hex << "\n";
            std::cerr << "eif0: " << std::hex << view.getEif0() << " eif1: " << view.getEif1() << " eif2: " << view.getEif2() << " eif3: " << view.getEif3() << " eif4: " << view.getEif4() << "\n";
            std::cerr << "view.getPacketSize(): " << (ntohl(words[0]) & 0xFFFF) << "\n";
            throw std::runtime_error("AckX error payloads len mismatch");
        }
        for (uint32_t val : {2147514162U,2147511795U,2147507502U,2147505163U,2147499226U,2147548006U,2147546560U,2147542376U,2147556279U,2147603558U,2147644926U,2147639544U,2147637158U}) {
            bool found = std::any_of(ackx_errs.begin(), ackx_errs.end(),
                                     [val](const ams::iface::vita::AckXView::ErrorPayload& err) {
                                         uint32_t rec = ackx_detail::pack_error_payload(err.subject, err.error_flags, err.error_enum_index);
                                         return rec == val; });
            if (!found) { throw std::runtime_error("AckX error payload missing"); }
        }
        std::vector<uint32_t> buf(2048, 0);
        AckXBuilder builder(buf.data(), buf.size());
        builder.setStreamId(2889635392U);
        builder.setTimestampInt(855256552U);
        builder.setTimestampFracHigh(104906255U);
        builder.setTimestampFracLow(312794864U);
        builder.setMessageId(1649174966U);
        builder.setSchX(true);
        builder.setScheduleRequestType(13U);
        builder.addError(AckXErrorSubject::Bandwidth, 2147514162U & 0xFFF80000U, 2147514162U & 0x3FF);
        builder.addError(AckXErrorSubject::RfRefFreq, 2147511795U & 0xFFF80000U, 2147511795U & 0x3FF);
        builder.addError(AckXErrorSubject::Gain, 2147507502U & 0xFFF80000U, 2147507502U & 0x3FF);
        builder.addError(AckXErrorSubject::SampleRate, 2147505163U & 0xFFF80000U, 2147505163U & 0x3FF);
        builder.addError(AckXErrorSubject::DataFormat, 2147499226U & 0xFFF80000U, 2147499226U & 0x3FF);
        builder.addError(AckXErrorSubject::Polarization, 2147548006U & 0xFFF80000U, 2147548006U & 0x3FF);
        builder.addError(AckXErrorSubject::Pointing3d, 2147546560U & 0xFFF80000U, 2147546560U & 0x3FF);
        builder.addError(AckXErrorSubject::BeamWidth, 2147542376U & 0xFFF80000U, 2147542376U & 0x3FF);
        builder.addError(AckXErrorSubject::FuncPriorityId, 2147556279U & 0xFFF80000U, 2147556279U & 0x3FF);
        builder.addError(AckXErrorSubject::Dwell, 2147603558U & 0xFFF80000U, 2147603558U & 0x3FF);
        builder.addError(AckXErrorSubject::RfFigureOfMerit, 2147644926U & 0xFFF80000U, 2147644926U & 0x3FF);
        builder.addError(AckXErrorSubject::AddressGroupIndex, 2147639544U & 0xFFF80000U, 2147639544U & 0x3FF);
        builder.addError(AckXErrorSubject::TxDigitalInputPower, 2147637158U & 0xFFF80000U, 2147637158U & 0x3FF);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "7ce0001bdc8aee3000aaaaaa04000c057337c599c074718e3d3f3799010904e0b6aae05b28a0801e62000000000000400020000021200000800075e080006e2c80005eaf8000568e80003ca58000f91b8000f5348000e5d980011b108001d538800275b68002608380025751";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        AckXView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for AckXView");
        }
        if (view.getStreamId() != 3700092464U) { throw std::runtime_error("Stream ID mismatch"); }
        auto ackx_errs = view.getParsedErrorPayloads();
        if (ackx_errs.size() != 13) {
            std::cerr << "Expected 13 error payloads, got " << ackx_errs.size() << " hex: " << hex << "\n";
            std::cerr << "eif0: " << std::hex << view.getEif0() << " eif1: " << view.getEif1() << " eif2: " << view.getEif2() << " eif3: " << view.getEif3() << " eif4: " << view.getEif4() << "\n";
            std::cerr << "view.getPacketSize(): " << (ntohl(words[0]) & 0xFFFF) << "\n";
            throw std::runtime_error("AckX error payloads len mismatch");
        }
        for (uint32_t val : {2147513824U,2147511852U,2147507887U,2147505806U,2147499173U,2147547419U,2147546420U,2147542489U,2147556112U,2147603768U,2147644854U,2147639427U,2147637073U}) {
            bool found = std::any_of(ackx_errs.begin(), ackx_errs.end(),
                                     [val](const ams::iface::vita::AckXView::ErrorPayload& err) {
                                         uint32_t rec = ackx_detail::pack_error_payload(err.subject, err.error_flags, err.error_enum_index);
                                         return rec == val; });
            if (!found) { throw std::runtime_error("AckX error payload missing"); }
        }
        std::vector<uint32_t> buf(2048, 0);
        AckXBuilder builder(buf.data(), buf.size());
        builder.setStreamId(3700092464U);
        builder.setTimestampInt(1933034905U);
        builder.setTimestampFracHigh(3228856718U);
        builder.setTimestampFracLow(1027553177U);
        builder.setMessageId(3064651867U);
        builder.setSchX(true);
        builder.setScheduleRequestType(14U);
        builder.addError(AckXErrorSubject::Bandwidth, 2147513824U & 0xFFF80000U, 2147513824U & 0x3FF);
        builder.addError(AckXErrorSubject::RfRefFreq, 2147511852U & 0xFFF80000U, 2147511852U & 0x3FF);
        builder.addError(AckXErrorSubject::Gain, 2147507887U & 0xFFF80000U, 2147507887U & 0x3FF);
        builder.addError(AckXErrorSubject::SampleRate, 2147505806U & 0xFFF80000U, 2147505806U & 0x3FF);
        builder.addError(AckXErrorSubject::DataFormat, 2147499173U & 0xFFF80000U, 2147499173U & 0x3FF);
        builder.addError(AckXErrorSubject::Polarization, 2147547419U & 0xFFF80000U, 2147547419U & 0x3FF);
        builder.addError(AckXErrorSubject::Pointing3d, 2147546420U & 0xFFF80000U, 2147546420U & 0x3FF);
        builder.addError(AckXErrorSubject::BeamWidth, 2147542489U & 0xFFF80000U, 2147542489U & 0x3FF);
        builder.addError(AckXErrorSubject::FuncPriorityId, 2147556112U & 0xFFF80000U, 2147556112U & 0x3FF);
        builder.addError(AckXErrorSubject::Dwell, 2147603768U & 0xFFF80000U, 2147603768U & 0x3FF);
        builder.addError(AckXErrorSubject::RfFigureOfMerit, 2147644854U & 0xFFF80000U, 2147644854U & 0x3FF);
        builder.addError(AckXErrorSubject::AddressGroupIndex, 2147639427U & 0xFFF80000U, 2147639427U & 0x3FF);
        builder.addError(AckXErrorSubject::TxDigitalInputPower, 2147637073U & 0xFFF80000U, 2147637073U & 0x3FF);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
}

void test_ExtensionDataContextPacket() {
    std::cout << "Testing ExtensionDataContextPacket...\n";
    {
        std::string hex = "58e0002068586eba00aaaaaa05000e058ae8905b6a702e2f6b8e869fa8a0801e6200000000000040002000002d0000006160a6b45a0cdd7cc0e3befd3875394c382c043f6f92f25e076e2bbaa00001c700000000b963f37fd72b6108eb67146a88bc539ce82c7d7ba9ba5a276db991020cdf742b610cf37374672cd9610e6a64";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ExtensionDataContextView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ExtensionDataContextView");
        }
        if (view.getStreamId() != 1750625978U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 7016791512978349436ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 13899162869778692428ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 942408767U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 8039754770475264954ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex8BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 3110335359U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 3609944328U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 3949401194U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 2294043548U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 16729884685856561703ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 1840877826U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getLateStartTime().value_or(0) != 927587777922265971ULL) { throw std::runtime_error("LateStartTime mismatch"); }
        if (view.getRejectReason().value_or(0) != 1952918745U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1628334692U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ExtensionDataContextBuilder builder(buf.data(), buf.size());
        builder.setStreamId(1750625978U);
        builder.setTimestampInt(2330497115U);
        builder.setTimestampFracHigh(1785736751U);
        builder.setTimestampFracLow(1804502687U);
        builder.addBandwidth(7016791512978349436ULL);
        builder.addRfRefFreq(13899162869778692428ULL);
        builder.addGain(942408767U);
        builder.addSampleRate(8039754770475264954ULL);
        builder.setDataFormat(DataFormat::Complex8BitSigned);
        builder.addPolarization(3110335359U);
        builder.addPointing3d(3609944328U);
        builder.addBeamWidth(3949401194U);
        builder.addFuncPriorityId(2294043548U);
        builder.addDwell(16729884685856561703ULL);
        builder.addRfFigureOfMerit(1840877826U);
        builder.addLateStartTime(927587777922265971ULL);
        builder.addRejectReason(1952918745U);
        builder.addAddressGroupIndex(1628334692U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "58e0002214f7ce8d00aaaaaa05000e058a175dfe59970043a66fd7f7a8a0801ee2000000000000400020000033000000c1156d6df319c1252702878b20500494ab61a7b137cc863bb31022f0a00001c700000000b7e6427c4fa03f269424aed5edcb8cb660141de932c5bd893e2b6091ce3714af5eddbbbf575aed2c272a6d8ea6846099c64ee6e3";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ExtensionDataContextView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ExtensionDataContextView");
        }
        if (view.getStreamId() != 351784589U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 13913146942828429605ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 2810958149044929684ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 2875303857U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 4020736158300381936ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex8BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPhaseOffset().value_or(0) != 3085320828U) { throw std::runtime_error("PhaseOffset mismatch"); }
        if (view.getPolarization().value_or(0) != 1335901990U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 2485432021U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 3989540022U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 1611931113U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 3658538669459595409ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 3459716271U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getEarlyStartTime().value_or(0) != 6835826239897005356ULL) { throw std::runtime_error("EarlyStartTime mismatch"); }
        if (view.getMaxDataPacketDwell().value_or(0) != 2822188575947514009ULL) { throw std::runtime_error("MaxDataPacketDwell mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 3327059683U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ExtensionDataContextBuilder builder(buf.data(), buf.size());
        builder.setStreamId(351784589U);
        builder.setTimestampInt(2316787198U);
        builder.setTimestampFracHigh(1503068227U);
        builder.setTimestampFracLow(2792347639U);
        builder.addBandwidth(13913146942828429605ULL);
        builder.addRfRefFreq(2810958149044929684ULL);
        builder.addGain(2875303857U);
        builder.addSampleRate(4020736158300381936ULL);
        builder.setDataFormat(DataFormat::Complex8BitSigned);
        builder.addPhaseOffset(3085320828U);
        builder.addPolarization(1335901990U);
        builder.addPointing3d(2485432021U);
        builder.addBeamWidth(3989540022U);
        builder.addFuncPriorityId(1611931113U);
        builder.addDwell(3658538669459595409ULL);
        builder.addRfFigureOfMerit(3459716271U);
        builder.addEarlyStartTime(6835826239897005356ULL);
        builder.addMaxDataPacketDwell(2822188575947514009ULL);
        builder.addAddressGroupIndex(3327059683U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "58e0001e44b591f700aaaaaa05000e05da09dfa0162f8a24e1b294dea8a0801ee20000000000004000200000210000000758e201d9d80b8d2e8d0e87364d7c87cc3ebdde57207246f2b43abf200003cf00000000b856d035c2171429b0cbc61f7da67785cafda61317d2582e38ba8abcb118f68d54aebd1b";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ExtensionDataContextView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ExtensionDataContextView");
        }
        if (view.getStreamId() != 1152750071U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 529421453793692557ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 3354353271355309191ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 3426663902U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 6278143529599646399ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPhaseOffset().value_or(0) != 3092697141U) { throw std::runtime_error("PhaseOffset mismatch"); }
        if (view.getPolarization().value_or(0) != 3256292393U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 2966144543U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 2108061573U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 3405620755U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 1716531363525069500ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 2971203213U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1420737819U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ExtensionDataContextBuilder builder(buf.data(), buf.size());
        builder.setStreamId(1152750071U);
        builder.setTimestampInt(3658080160U);
        builder.setTimestampFracHigh(372214308U);
        builder.setTimestampFracLow(3786577118U);
        builder.addBandwidth(529421453793692557ULL);
        builder.addRfRefFreq(3354353271355309191ULL);
        builder.addGain(3426663902U);
        builder.addSampleRate(6278143529599646399ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPhaseOffset(3092697141U);
        builder.addPolarization(3256292393U);
        builder.addPointing3d(2966144543U);
        builder.addBeamWidth(2108061573U);
        builder.addFuncPriorityId(3405620755U);
        builder.addDwell(1716531363525069500ULL);
        builder.addRfFigureOfMerit(2971203213U);
        builder.addAddressGroupIndex(1420737819U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "58e00023455ac76200aaaaaa05000e05405bfdc9314d34412f65fafaa8a0801e6200000000000040002000003d20000031b1b0993a3c563e2defe19388bd13d14639447bf96b648a8da8eee4200003cf0000000048ca76517a8d03aa5738811df72ada9bdc99e04c10ba58e37de31a5126d794d3f2f9e5fafe716b14c3b290d0616074596dc7cac7bd767e35";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ExtensionDataContextView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ExtensionDataContextView");
        }
        if (view.getStreamId() != 1163577186U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 3580837350889772606ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 3310112274911138769ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 1178158203U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 17972569284197019364ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 1221228113U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 2056061866U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 1463320861U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 4146780827U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 15895982977083660515ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 2112035409U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getEarlyStartTime().value_or(0) != 2798869331469526522ULL) { throw std::runtime_error("EarlyStartTime mismatch"); }
        if (view.getLateStartTime().value_or(0) != 18334553294928777424ULL) { throw std::runtime_error("LateStartTime mismatch"); }
        if (view.getRejectReason().value_or(0) != 1633711193U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 1841810119U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 3178659381U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ExtensionDataContextBuilder builder(buf.data(), buf.size());
        builder.setStreamId(1163577186U);
        builder.setTimestampInt(1079770569U);
        builder.setTimestampFracHigh(827143233U);
        builder.setTimestampFracLow(795212538U);
        builder.addBandwidth(3580837350889772606ULL);
        builder.addRfRefFreq(3310112274911138769ULL);
        builder.addGain(1178158203U);
        builder.addSampleRate(17972569284197019364ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(1221228113U);
        builder.addPointing3d(2056061866U);
        builder.addBeamWidth(1463320861U);
        builder.addFuncPriorityId(4146780827U);
        builder.addDwell(15895982977083660515ULL);
        builder.addRfFigureOfMerit(2112035409U);
        builder.addEarlyStartTime(2798869331469526522ULL);
        builder.addLateStartTime(18334553294928777424ULL);
        builder.addRejectReason(1633711193U);
        builder.addAddressGroupIndex(1841810119U);
        builder.addTxDigitalInputPower(3178659381U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "58e000233605bf5400aaaaaa05000e05a911d1922834e4c01337739ea8a0801e62000000000000400020000037200000980402a24a8ff8103b4206c5b4fb0eb9743b65a2aff8754dec856f37200003cf00000000246998e80f44704fcae9b4a7ebd34616706c5c568a3c3b5e7010f719e3b137fcbc0a6a5d176132edc19ad58ca6c9537fea83bf00d0725b5c";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        ExtensionDataContextView view(span_data);
        if (!view.isValid()) {
            std::cerr << "View Invalid. Word1: " << std::hex << ntohl(words[0]) << " Words Size: " << words.size() << "\n";
            std::cerr << "OUI: " << std::hex << ntohl(words[2]) << " Codes: " << ntohl(words[3]) << "\n";
            std::cerr << "CIF0: " << std::hex << ntohl(words[9]) << "\n";
            throw std::runtime_error("Invalid View for ExtensionDataContextView");
        }
        if (view.getStreamId() != 906346324U) { throw std::runtime_error("Stream ID mismatch"); }
        if (view.getBandwidth().value_or(0) != 10953883089730795536ULL) { throw std::runtime_error("Bandwidth mismatch"); }
        if (view.getRfRefFreq().value_or(0) != 4269982842915327673ULL) { throw std::runtime_error("RfRefFreq mismatch"); }
        if (view.getGain().value_or(0) != 1950049698U) { throw std::runtime_error("Gain mismatch"); }
        if (view.getSampleRate().value_or(0) != 12680013728402730807ULL) { throw std::runtime_error("SampleRate mismatch"); }
        auto data_format = view.getParsedDataFormat();
        if (!data_format || *data_format != DataFormat::Complex16BitSigned) { throw std::runtime_error("DataFormat mismatch"); }
        if (view.getPolarization().value_or(0) != 610900200U) { throw std::runtime_error("Polarization mismatch"); }
        if (view.getPointing3d().value_or(0) != 256143439U) { throw std::runtime_error("Pointing3d mismatch"); }
        if (view.getBeamWidth().value_or(0) != 3404313767U) { throw std::runtime_error("BeamWidth mismatch"); }
        if (view.getFuncPriorityId().value_or(0) != 3956491798U) { throw std::runtime_error("FuncPriorityId mismatch"); }
        if (view.getDwell().value_or(0) != 8100951356488825694ULL) { throw std::runtime_error("Dwell mismatch"); }
        if (view.getRfFigureOfMerit().value_or(0) != 1880160025U) { throw std::runtime_error("RfFigureOfMerit mismatch"); }
        if (view.getEarlyStartTime().value_or(0) != 16406956476113513053ULL) { throw std::runtime_error("EarlyStartTime mismatch"); }
        if (view.getRejectReason().value_or(0) != 392245997U) { throw std::runtime_error("RejectReason mismatch"); }
        if (view.getMaxDataPacketDwell().value_or(0) != 13950697595803882367ULL) { throw std::runtime_error("MaxDataPacketDwell mismatch"); }
        if (view.getAddressGroupIndex().value_or(0) != 3934502656U) { throw std::runtime_error("AddressGroupIndex mismatch"); }
        if (view.getTxDigitalInputPower().value_or(0) != 3497155420U) { throw std::runtime_error("TxDigitalInputPower mismatch"); }
        std::vector<uint32_t> buf(2048, 0);
        ExtensionDataContextBuilder builder(buf.data(), buf.size());
        builder.setStreamId(906346324U);
        builder.setTimestampInt(2836517266U);
        builder.setTimestampFracHigh(674555072U);
        builder.setTimestampFracLow(322401182U);
        builder.addBandwidth(10953883089730795536ULL);
        builder.addRfRefFreq(4269982842915327673ULL);
        builder.addGain(1950049698U);
        builder.addSampleRate(12680013728402730807ULL);
        builder.setDataFormat(DataFormat::Complex16BitSigned);
        builder.addPolarization(610900200U);
        builder.addPointing3d(256143439U);
        builder.addBeamWidth(3404313767U);
        builder.addFuncPriorityId(3956491798U);
        builder.addDwell(8100951356488825694ULL);
        builder.addRfFigureOfMerit(1880160025U);
        builder.addEarlyStartTime(16406956476113513053ULL);
        builder.addRejectReason(392245997U);
        builder.addMaxDataPacketDwell(13950697595803882367ULL);
        builder.addAddressGroupIndex(3934502656U);
        builder.addTxDigitalInputPower(3497155420U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Builder Size mismatch: expected " + std::to_string(words.size()) + " got " + std::to_string(builder_size)); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Builder Bytes mismatch");
        }
    }
}

void test_DataPacket() {
    std::cout << "Testing DataPacket...\n";
    {
        std::string hex = "1ce0000ef814010200aaaaaa04000d05785299f46889803e292bd156b194990bf1f8343e8cd321b0746f78915084324252c2122100c00000";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        DataPacketView view(span_data);
        if (!view.isValid()) { throw std::runtime_error("Invalid Data View"); }
        if (view.getStreamId() != 4162060546U) { throw std::runtime_error("Data Stream ID mismatch"); }
        auto payload_span = view.getPayload();
        if (payload_span.size() != 6U) { throw std::runtime_error("Data Payload Len mismatch"); }
        std::vector<uint32_t> buf(1024, 0);
        DataPacketBuilder builder(buf.data(), buf.size());
        builder.setStreamId(4162060546U);
        builder.setTimestampInt(2018679284U);
        builder.setTimestampFracHigh(1753841726U);
        builder.setTimestampFracLow(690737494U);
        std::vector<uint32_t> p_buf = host_to_network_words({2979305739U,4059575358U,2362646960U,1953462417U,1350840898U,1388450337U});
        builder.setPayload(p_buf);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Data Builder Size mismatch"); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Data Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "1ce00012fcf5618800aaaaaa04000d058ae769ed69ca97d2c1a6423b0d366dfc49bc473f7c16128dcc9fd334b5b453ca687213f91d0bc9bdf27292b6276aa6ceb495db4e00c00000";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        DataPacketView view(span_data);
        if (!view.isValid()) { throw std::runtime_error("Invalid Data View"); }
        if (view.getStreamId() != 4243939720U) { throw std::runtime_error("Data Stream ID mismatch"); }
        auto payload_span = view.getPayload();
        if (payload_span.size() != 10U) { throw std::runtime_error("Data Payload Len mismatch"); }
        std::vector<uint32_t> buf(1024, 0);
        DataPacketBuilder builder(buf.data(), buf.size());
        builder.setStreamId(4243939720U);
        builder.setTimestampInt(2330421741U);
        builder.setTimestampFracHigh(1774884818U);
        builder.setTimestampFracLow(3248898619U);
        std::vector<uint32_t> p_buf = host_to_network_words({221670908U,1237075775U,2081821325U,3433026356U,3048494026U,1752306681U,487311805U,4067594934U,661300942U,3029719886U});
        builder.setPayload(p_buf);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Data Builder Size mismatch"); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Data Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "1ce0000d78e3654b00aaaaaa04000d052507418111df12d7dabac50d81fb18b3d20f87d0260a596289e06ab3585a0afa00c00000";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        DataPacketView view(span_data);
        if (!view.isValid()) { throw std::runtime_error("Invalid Data View"); }
        if (view.getStreamId() != 2028168523U) { throw std::runtime_error("Data Stream ID mismatch"); }
        auto payload_span = view.getPayload();
        if (payload_span.size() != 5U) { throw std::runtime_error("Data Payload Len mismatch"); }
        std::vector<uint32_t> buf(1024, 0);
        DataPacketBuilder builder(buf.data(), buf.size());
        builder.setStreamId(2028168523U);
        builder.setTimestampInt(621232513U);
        builder.setTimestampFracHigh(299832023U);
        builder.setTimestampFracLow(3669673229U);
        std::vector<uint32_t> p_buf = host_to_network_words({2180716723U,3524233168U,638212450U,2313185971U,1482296058U});
        builder.setPayload(p_buf);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Data Builder Size mismatch"); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Data Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "1ce000088b1e3b9d00aaaaaa04000d05b28f41de9261549dc68a152f00c00000";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        DataPacketView view(span_data);
        if (!view.isValid()) { throw std::runtime_error("Invalid Data View"); }
        if (view.getStreamId() != 2334014365U) { throw std::runtime_error("Data Stream ID mismatch"); }
        auto payload_span = view.getPayload();
        if (payload_span.size() != 0U) { throw std::runtime_error("Data Payload Len mismatch"); }
        std::vector<uint32_t> buf(1024, 0);
        DataPacketBuilder builder(buf.data(), buf.size());
        builder.setStreamId(2334014365U);
        builder.setTimestampInt(2995732958U);
        builder.setTimestampFracHigh(2455852189U);
        builder.setTimestampFracLow(3330938159U);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Data Builder Size mismatch"); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Data Builder Bytes mismatch");
        }
    }
    {
        std::string hex = "1ce0000961985d5400aaaaaa04000d0526f05fcff6febc0ed85480f074f93d1700c00000";
        auto words = hex_to_words(hex);
        std::span<const uint32_t> span_data(words);
        DataPacketView view(span_data);
        if (!view.isValid()) { throw std::runtime_error("Invalid Data View"); }
        if (view.getStreamId() != 1637375316U) { throw std::runtime_error("Data Stream ID mismatch"); }
        auto payload_span = view.getPayload();
        if (payload_span.size() != 1U) { throw std::runtime_error("Data Payload Len mismatch"); }
        std::vector<uint32_t> buf(1024, 0);
        DataPacketBuilder builder(buf.data(), buf.size());
        builder.setStreamId(1637375316U);
        builder.setTimestampInt(653287375U);
        builder.setTimestampFracHigh(4143889422U);
        builder.setTimestampFracLow(3629416688U);
        std::vector<uint32_t> p_buf = host_to_network_words({1962491159U});
        builder.setPayload(p_buf);
        size_t builder_size = builder.finalize();
        if (builder_size != words.size()) { throw std::runtime_error("Data Builder Size mismatch"); }
        if (std::memcmp(buf.data(), words.data(), builder_size * 4) != 0) {
            for(size_t j=0; j<builder_size; j++) {
                if (buf[j] != words[j]) { std::cerr << "Mismatch at word " << j << ": expected " << std::hex << ntohl(words[j]) << " got " << ntohl(buf[j]) << "\n"; }
            }
            throw std::runtime_error("Data Builder Bytes mismatch");
        }
    }
}

auto main() -> int {
    try {
        test_ControlScheduleRequestPacket();
        test_ExtensionDataContextPacket();
        test_ScheduleAckAckRPacket();
        test_ExecutionAckAckXPacket();
        test_DataPacket();
        std::cout << "All generated roundtrip tests passed.\n";
    } catch (const std::exception& e) {
        std::cerr << "Test failed: " << e.what() << "\n";
        return 1;
    }
    return 0;
}
